version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_GestionTutorias
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d 